version: 2

jobs:
  build:
      docker:
        - image: circleci/node:6.5.0

steps:
  - checkout
  - run: set -o pipefail && npm -s test > ${CIRCLE_TEST_REPORTS}/testresults.xml
  - run: npm run lint
  - run: npm run createcoverage
  - run: set -o pipefail && npm -s run reportcoverage
  - run: cp -R ./coverage/* ${CIRCLE_TEST_REPORTS}
  - run: aws s3 cp ./coverage/lcov.info s3://elasticbeanstalk-us-west-2-886403637725/sonar/deploytest/

  - deploy:
      releases:
        branch: master
        commands:
          - sh ./scripts/ci-deploy.sh
